# 数据库部分
TABLE_YJYG = 'ashareprofitnotice'
YJYG_COLUMN = ['S_INFO_WINDCODE', 'S_PROFITNOTICE_DATE']

# 要处理的数据库字段
MD5_COLUMN = ['S_INFO_WINDCODE', 'S_PROFITNOTICE_DATE']
MD5_NAME = 'ID_MD5'
INSERT_STRUCT = {MD5_NAME: 'VARCHAR(255)', 'S_INFO_CODE': 'VARCHAR(50)',
                 'S_PROFITNOTICE_DATE': 'DATE', 'PK': MD5_NAME}
INSERT_TABLE = 'WIND_YJYG_COMPARE'
